detectors:
  UtilityFunction:
    exclude:
      - 'options'
  IrresponsibleModule:
    exclude:
      - 'HomePage'
      - 'SignInPage'
      - 'SignUpPage'
      - 'HeaderSection'
      - 'MenuSection'
